[package]
name = "image-fetcher"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mcp-core = "0.1"
reqwest = { version = "0.11", features = ["blocking"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"